# Databricks notebook source
# MAGIC %md
# MAGIC # Gold Layer — Healthcare Data Pipeline
# MAGIC ## Medallion Architecture on Azure Databricks
# MAGIC
# MAGIC This notebook builds the Gold layer on top of the validated Silver table.
# MAGIC
# MAGIC The Gold layer does not store individual records. It stores **answers**.
# MAGIC Every table here is purpose-built for a specific analytical domain —
# MAGIC clinical performance, financial analysis, or patient demographics.
# MAGIC
# MAGIC Only records that passed all Silver data quality checks (`dq_passed = True`)
# MAGIC are included in Gold aggregations. This is a deliberate decision, Gold
# MAGIC tables are consumed directly by reporting tools and business stakeholders.
# MAGIC Untrustworthy records must not reach this layer.
# MAGIC
# MAGIC ### Gold Tables built in this notebook
# MAGIC
# MAGIC | Table | Domain | Description |
# MAGIC |---|---|---|
# MAGIC | `gold.condition_summary` | Clinical | Aggregated metrics per medical condition |
# MAGIC | `gold.billing_summary` | Financial | Billing breakdown by insurance, age group, condition |
# MAGIC | `gold.patient_demographics` | Population | Patient distribution by age group, gender, condition |
# MAGIC
# MAGIC **Source Table :** `silver.healthcare_clean`
# MAGIC **Format       :** Delta Lake
# MAGIC **Database     :** `gold`

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 1 — Load Configuration and Read Silver Table
# MAGIC
# MAGIC Reads the validated Silver Delta table as the source for all Gold
# MAGIC aggregations. Only records where `dq_passed = True` are carried
# MAGIC forward, failed records remain in Silver for investigation but
# MAGIC are excluded from all Gold layer analytics.

# COMMAND ----------

# MAGIC %run "/Workspace/Users/malika.mujahid@studentambassadors.com/utils_config"

# COMMAND ----------

# DBTITLE 1,exec config
cfg = load_config("/Workspace/Users/malika.mujahid@studentambassadors.com/config (1).json")
print(cfg["storage_account_name"])

# COMMAND ----------

# DBTITLE 1,read silver — dq passed records only
import pyspark.sql.functions as F
from pyspark.sql.types import DecimalType

df_silver = spark.table("silver.healthcare_clean")

# Filter to DQ passed records only
df_gold_base = df_silver.filter(F.col("dq_passed") == True)

total_silver = df_silver.count()
total_gold   = df_gold_base.count()
excluded     = total_silver - total_gold

print(f"{'─' * 45}")
print(f"  Silver total records : {total_silver:,}")
print(f"  Gold base records    : {total_gold:,}")
print(f"  Excluded (DQ failed) : {excluded:,}")
print(f"{'─' * 45}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 2 - gold.condition_summary
# MAGIC
# MAGIC This table is the **clinical analytics** table. It answers the most
# MAGIC important operational questions in a healthcare dataset, as, how long
# MAGIC are patients staying, what are they costing, and which conditions
# MAGIC are producing the most abnormal outcomes.
# MAGIC
# MAGIC ### Metrics included
# MAGIC
# MAGIC | Metric | Description |
# MAGIC |---|---|
# MAGIC | `total_patients` | Total number of patients per condition |
# MAGIC | `avg_length_of_stay_days` | Average days between admission and discharge |
# MAGIC | `max_length_of_stay_days` | Longest recorded stay for this condition |
# MAGIC | `avg_billing_amount` | Average billing amount per patient |
# MAGIC | `total_billing_amount` | Total revenue generated by condition |
# MAGIC | `most_common_admission_type` | Most frequent admission type (Urgent / Emergency / Elective) |
# MAGIC | `abnormal_test_rate_pct` | Percentage of patients with abnormal test results |
# MAGIC
# MAGIC ### Why this table matters
# MAGIC In real healthcare analytics, `condition_summary` feeds:
# MAGIC - Hospital resource planning dashboards
# MAGIC - Clinical outcome monitoring
# MAGIC - Cost-per-condition benchmarking reports

# COMMAND ----------

# DBTITLE 1,build condition summary
from pyspark.sql import Window

# Most common admission type per condition
# Using a window function to rank admission types by frequency
admission_counts = (
    df_gold_base
    .groupBy("medical_condition", "admission_type")
    .agg(F.count("*").alias("admission_count"))
)

window_spec = Window.partitionBy("medical_condition").orderBy(
    F.col("admission_count").desc()
)

most_common_admission = (
    admission_counts
    .withColumn("rank", F.rank().over(window_spec))
    .filter(F.col("rank") == 1)
    .select("medical_condition", 
            F.col("admission_type").alias("most_common_admission_type"))
)

# Core condition aggregations
condition_agg = (
    df_gold_base
    .groupBy("medical_condition")
    .agg(
        F.count("*")
         .alias("total_patients"),
        F.round(F.avg("length_of_stay_days"), 2)
         .alias("avg_length_of_stay_days"),
        F.max("length_of_stay_days")
         .alias("max_length_of_stay_days"),
        F.round(F.avg("billing_amount"), 2)
         .alias("avg_billing_amount"),
        F.round(F.sum("billing_amount"), 2)
         .alias("total_billing_amount"),
        F.round(
            F.sum(F.when(F.col("test_results") == "Abnormal", 1)
                   .otherwise(0)) * 100.0 / F.count("*"), 2
        ).alias("abnormal_test_rate_pct")
    )
)

# Join most common admission type
df_condition_summary = condition_agg.join(
    most_common_admission,
    on="medical_condition",
    how="left"
).orderBy(F.col("total_patients").desc())

print("condition_summary built")
display(df_condition_summary)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 3 — Write gold.condition_summary to Delta Lake (Incremental MERGE)
# MAGIC
# MAGIC Writes the condition summary table using a Delta Lake MERGE pattern
# MAGIC rather than a full overwrite.
# MAGIC
# MAGIC **Why MERGE instead of overwrite?**
# MAGIC
# MAGIC Gold tables store aggregations, not individual records. When new patient
# MAGIC admissions arrive in silver, existing condition metrics change. Average
# MAGIC billing shifts, length of stay updates, abnormal test rates fluctuate.
# MAGIC
# MAGIC A full overwrite recalculates everything from scratch every run. This is
# MAGIC correct but inefficient at scale. A MERGE pattern updates only the
# MAGIC conditions where data has changed, leaving untouched conditions as they are.
# MAGIC
# MAGIC This mirrors production-grade pipeline design where Gold tables serve
# MAGIC live dashboards and cannot afford full rebuilds on every pipeline run.
# MAGIC
# MAGIC **MERGE logic:**
# MAGIC - If `medical_condition` already exists in gold → UPDATE all metrics
# MAGIC - If `medical_condition` is new → INSERT as a new row

# COMMAND ----------

# DBTITLE 1,write gold.condition_summary — incremental merge
from delta.tables import DeltaTable

spark.sql("CREATE DATABASE IF NOT EXISTS gold")
print(" Gold database ready")

gold_table_name = "gold.condition_summary"

table_exists = spark.catalog.tableExists(gold_table_name)

if not table_exists:
    (
        df_condition_summary
        .write
        .format("delta")
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(gold_table_name)
    )
    print(f" {gold_table_name} created on first run")

else:
    delta_table = DeltaTable.forName(spark, gold_table_name)
    (
        delta_table.alias("existing")
        .merge(
            df_condition_summary.alias("updates"),
            "existing.medical_condition = updates.medical_condition"
        )
        .whenMatchedUpdateAll()
        .whenNotMatchedInsertAll()
        .execute()
    )
    print(f"{gold_table_name} updated via MERGE")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 4 — Optimise gold.condition_summary
# MAGIC
# MAGIC Runs `OPTIMIZE` on the Gold table to compact small Delta files
# MAGIC into larger, more efficient files for query performance.
# MAGIC
# MAGIC `ZORDER BY medical_condition` co-locates data by condition, the
# MAGIC primary filter used in all downstream queries on this table.
# MAGIC This is a Databricks-specific Delta Lake feature that significantly
# MAGIC reduces query scan time as the dataset grows over time.
# MAGIC
# MAGIC In a production pipeline, OPTIMIZE would be scheduled as a
# MAGIC maintenance job running after each pipeline execution.

# COMMAND ----------

# DBTITLE 1,optimise and zorder
spark.sql("OPTIMIZE gold.condition_summary ZORDER BY (medical_condition)")
print("Optimisation complete")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 5 — Validate and Preview gold.condition_summary
# MAGIC
# MAGIC Reads back from the Gold table to confirm the write was successful
# MAGIC and the aggregations are producing meaningful clinical insights.
# MAGIC
# MAGIC The summary printed below represents the kind of analytical value
# MAGIC the Gold layer delivers — actionable numbers, not raw records.

# COMMAND ----------

# DBTITLE 1,validate condition summary
df_check = spark.table("gold.condition_summary")

print(f"gold.condition_summary record count: {df_check.count()}")
print(f"{'─' * 55}")

print("\n Clinical Insights from Gold Layer:\n")

# Condition with highest avg billing
top_billing = df_check.orderBy(
    F.col("avg_billing_amount").desc()
).first()
print(f" Highest avg billing   : "
      f"{top_billing['medical_condition']} "
      f"(£{float(top_billing['avg_billing_amount']):,.2f})")

# Condition with longest avg stay
top_stay = df_check.orderBy(
    F.col("avg_length_of_stay_days").desc()
).first()
print(f" Longest avg stay      : "
      f"{top_stay['medical_condition']} "
      f"({top_stay['avg_length_of_stay_days']} days)")

# Condition with highest abnormal test rate
top_abnormal = df_check.orderBy(
    F.col("abnormal_test_rate_pct").desc()
).first()
print(f" Highest abnormal rate : "
      f"{top_abnormal['medical_condition']} "
      f"({top_abnormal['abnormal_test_rate_pct']}%)")

print(f"\n{'─' * 55}")

display(df_check)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 6 — gold.billing_summary
# MAGIC
# MAGIC This table is the **financial analytics** table. It breaks down
# MAGIC billing and cost data across insurance providers, age groups,
# MAGIC and medical conditions.
# MAGIC
# MAGIC ### Metrics included
# MAGIC
# MAGIC | Metric | Description |
# MAGIC |---|---|
# MAGIC | `total_patients` | Total patients in this segment |
# MAGIC | `total_billing_amount` | Total revenue for this segment |
# MAGIC | `avg_billing_amount` | Average billing per patient |
# MAGIC | `min_billing_amount` | Lowest billing amount in segment |
# MAGIC | `max_billing_amount` | Highest billing amount in segment |
# MAGIC
# MAGIC ### Why this table matters
# MAGIC In real healthcare analytics, `billing_summary` feeds:
# MAGIC - Insurance provider performance dashboards
# MAGIC - Revenue analysis by demographic
# MAGIC - Cost benchmarking across conditions and age groups

# COMMAND ----------

# DBTITLE 1,build billing summary
df_billing_summary = (
    df_gold_base
    .groupBy(
        "insurance_provider",
        "age_group",
        "medical_condition"
    )
    .agg(
        F.count("*")
         .alias("total_patients"),
        F.round(F.sum("billing_amount"), 2)
         .alias("total_billing_amount"),
        F.round(F.avg("billing_amount"), 2)
         .alias("avg_billing_amount"),
        F.round(F.min("billing_amount"), 2)
         .alias("min_billing_amount"),
        F.round(F.max("billing_amount"), 2)
         .alias("max_billing_amount")
    )
    .orderBy(F.col("total_billing_amount").desc())
)

print("billing_summary built")
display(df_billing_summary)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 7 — Write gold.billing_summary (Incremental MERGE)
# MAGIC
# MAGIC Writes the billing summary using the same Delta Lake MERGE
# MAGIC pattern as `gold.condition_summary`.
# MAGIC
# MAGIC The merge key is a combination of `insurance_provider`,
# MAGIC `age_group`, and `medical_condition`, together these
# MAGIC uniquely identify each row in the billing summary table.
# MAGIC
# MAGIC **MERGE logic:**
# MAGIC - If the combination already exists in gold → UPDATE all metrics
# MAGIC - If it is a new combination → INSERT as a new row

# COMMAND ----------

# DBTITLE 1,write gold.billing_summary — incremental merge
from delta.tables import DeltaTable

gold_table_name = "gold.billing_summary"

table_exists = spark.catalog.tableExists(gold_table_name)

if not table_exists:
    (
        df_billing_summary
        .write
        .format("delta")
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(gold_table_name)
    )
    print(f" {gold_table_name} created on first run")

else:
    delta_table = DeltaTable.forName(spark, gold_table_name)
    (
        delta_table.alias("existing")
        .merge(
            df_billing_summary.alias("updates"),
            """existing.insurance_provider = updates.insurance_provider
               AND existing.age_group = updates.age_group
               AND existing.medical_condition = updates.medical_condition"""
        )
        .whenMatchedUpdateAll()
        .whenNotMatchedInsertAll()
        .execute()
    )
    print(f"{gold_table_name} updated via MERGE")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 8 — Optimise gold.billing_summary
# MAGIC
# MAGIC Runs `OPTIMIZE` with `ZORDER BY insurance_provider` since
# MAGIC the most common filter on this table will be by insurance
# MAGIC provider, for example, comparing costs across Blue Cross,
# MAGIC Medicare, Cigna, and UnitedHealthcare.

# COMMAND ----------

# DBTITLE 1,optimise and zorder
spark.sql("""
    OPTIMIZE gold.billing_summary
    ZORDER BY (insurance_provider, medical_condition)
""")
print(" Optimisation complete")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 9 — Validate gold.billing_summary
# MAGIC
# MAGIC Reads back from the Gold table and prints key financial
# MAGIC insights across the dataset.

# COMMAND ----------

# DBTITLE 1,validate billing summary
df_check = spark.table("gold.billing_summary")

print(f"gold.billing_summary record count: {df_check.count()}")
print(f"{'─' * 55}")

print("\n Financial Insights from Gold Layer:\n")

# Insurance provider with highest total billing
top_insurer = df_check.groupBy("insurance_provider") \
    .agg(F.sum("total_billing_amount").alias("grand_total")) \
    .orderBy(F.col("grand_total").desc()) \
    .first()
print(f"  Highest billing insurer : {top_insurer['insurance_provider']} "
      f"(£{float(top_insurer['grand_total']):,.2f})")

# Age group with highest avg billing
top_age = df_check.groupBy("age_group") \
    .agg(F.avg("avg_billing_amount").alias("avg_bill")) \
    .orderBy(F.col("avg_bill").desc()) \
    .first()
print(f"Highest billing age group : {top_age['age_group']} "
      f"(£{float(top_age['avg_bill']):,.2f} avg)")

# Condition with highest total billing
top_condition = df_check.groupBy("medical_condition") \
    .agg(F.sum("total_billing_amount").alias("condition_total")) \
    .orderBy(F.col("condition_total").desc()) \
    .first()
print(f"Highest billing condition : {top_condition['medical_condition']} "
      f"(£{float(top_condition['condition_total']):,.2f})")

print(f"\n{'─' * 55}")

display(df_check)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 10 — gold.patient_demographics
# MAGIC
# MAGIC This table is the **population analytics** table. It answers
# MAGIC demographic-level questions about the patient population —
# MAGIC how patients are distributed across age groups, genders,
# MAGIC and medical conditions, and what their average clinical
# MAGIC and financial metrics look like.
# MAGIC
# MAGIC ### Metrics included
# MAGIC
# MAGIC | Metric | Description |
# MAGIC |---|---|
# MAGIC | `total_patients` | Total patients in this segment |
# MAGIC | `avg_age` | Average age of patients in this segment |
# MAGIC | `avg_length_of_stay_days` | Average days between admission and discharge |
# MAGIC | `avg_billing_amount` | Average billing amount per patient |
# MAGIC | `total_billing_amount` | Total billing for this demographic segment |
# MAGIC | `abnormal_test_rate_pct` | Percentage of abnormal test results |
# MAGIC
# MAGIC ### Why this table matters
# MAGIC In real healthcare analytics, `patient_demographics` feeds:
# MAGIC - Population health management dashboards
# MAGIC - Gender and age-based outcome reporting
# MAGIC - Demographic cost analysis for resource planning

# COMMAND ----------

# DBTITLE 1,build patient demographics
df_patient_demographics = (
    df_gold_base
    .groupBy(
        "age_group",
        "gender",
        "medical_condition"
    )
    .agg(
        F.count("*")
         .alias("total_patients"),
        F.round(F.avg("age"), 1)
         .alias("avg_age"),
        F.round(F.avg("length_of_stay_days"), 2)
         .alias("avg_length_of_stay_days"),
        F.round(F.avg("billing_amount"), 2)
         .alias("avg_billing_amount"),
        F.round(F.sum("billing_amount"), 2)
         .alias("total_billing_amount"),
        F.round(
            F.sum(F.when(F.col("test_results") == "Abnormal", 1)
                   .otherwise(0)) * 100.0 / F.count("*"), 2
        ).alias("abnormal_test_rate_pct")
    )
    .orderBy(
        F.col("age_group"),
        F.col("gender"),
        F.col("total_patients").desc()
    )
)

print(" patient_demographics built")
display(df_patient_demographics)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 11 — Write gold.patient_demographics (Incremental MERGE)
# MAGIC
# MAGIC Writes the patient demographics table using the same Delta
# MAGIC Lake MERGE pattern as the previous Gold tables.
# MAGIC
# MAGIC The merge key is a combination of `age_group`, `gender`,
# MAGIC and `medical_condition` — together these uniquely identify
# MAGIC each demographic segment in the table.
# MAGIC
# MAGIC **MERGE logic:**
# MAGIC - If the segment already exists in gold → UPDATE all metrics
# MAGIC - If it is a new segment → INSERT as a new row

# COMMAND ----------

# DBTITLE 1,write gold.patient_demographics — incremental merge
from delta.tables import DeltaTable

gold_table_name = "gold.patient_demographics"

table_exists = spark.catalog.tableExists(gold_table_name)

if not table_exists:
    (
        df_patient_demographics
        .write
        .format("delta")
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(gold_table_name)
    )
    print(f"{gold_table_name} created on first run")

else:
    delta_table = DeltaTable.forName(spark, gold_table_name)
    (
        delta_table.alias("existing")
        .merge(
            df_patient_demographics.alias("updates"),
            """existing.age_group = updates.age_group
               AND existing.gender = updates.gender
               AND existing.medical_condition = updates.medical_condition"""
        )
        .whenMatchedUpdateAll()
        .whenNotMatchedInsertAll()
        .execute()
    )
    print(f" {gold_table_name} updated via MERGE")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 12 — Optimise gold.patient_demographics
# MAGIC
# MAGIC Runs `OPTIMIZE` with `ZORDER BY age_group, gender` since
# MAGIC the most common filters on this table will be demographic
# MAGIC — filtering by age group or gender for population-level
# MAGIC reporting and dashboarding.

# COMMAND ----------

# DBTITLE 1,optimise and zorder
spark.sql("""
    OPTIMIZE gold.patient_demographics
    ZORDER BY (age_group, gender)
""")
print(" Optimisation complete")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 13 — Validate gold.patient_demographics
# MAGIC
# MAGIC Reads back from the Gold table and prints key demographic
# MAGIC insights across the patient population.

# COMMAND ----------

# DBTITLE 1,validate patient demographics
df_check = spark.table("gold.patient_demographics")

print(f" gold.patient_demographics record count: {df_check.count()}")
print(f"{'─' * 55}")

print("\n Demographic Insights from Gold Layer:\n")

# Age group with most patients
top_age = df_check.groupBy("age_group") \
    .agg(F.sum("total_patients").alias("total")) \
    .orderBy(F.col("total").desc()) \
    .first()
print(f"   Largest age group       : {top_age['age_group']} "
      f"({top_age['total']:,} patients)")

# Gender with highest avg billing
top_gender = df_check.groupBy("gender") \
    .agg(F.avg("avg_billing_amount").alias("avg_bill")) \
    .orderBy(F.col("avg_bill").desc()) \
    .first()
print(f"  Highest billing gender  : {top_gender['gender']} "
      f"(£{float(top_gender['avg_bill']):,.2f} avg)")

# Condition with highest abnormal rate across all demographics
top_abnormal = df_check.groupBy("medical_condition") \
    .agg(F.avg("abnormal_test_rate_pct").alias("avg_abnormal")) \
    .orderBy(F.col("avg_abnormal").desc()) \
    .first()
print(f"  Highest abnormal rate   : {top_abnormal['medical_condition']} "
      f"({round(float(top_abnormal['avg_abnormal']), 2)}%)")

print(f"\n{'─' * 55}")

display(df_check)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Gold Layer Complete — Medallion Architecture End to End
# MAGIC
# MAGIC All three Gold tables have been successfully built, written
# MAGIC to Delta Lake, and optimised.
# MAGIC
# MAGIC | Table | Domain | Status |
# MAGIC |---|---|---|
# MAGIC | `gold.condition_summary` | Clinical Analytics |  Complete |
# MAGIC | `gold.billing_summary` | Financial Analytics | Complete |
# MAGIC | `gold.patient_demographics` | Population Analytics |  Complete |
# MAGIC
# MAGIC ### What this pipeline delivers
# MAGIC
# MAGIC Starting from a raw healthcare CSV in Azure Blob Storage,
# MAGIC this pipeline now produces three business-ready Gold tables
# MAGIC that can be consumed directly by Power BI or any downstream
# MAGIC reporting tool.
# MAGIC
# MAGIC **Bronze** → Raw ingestion, immutable, traceable
# MAGIC **Silver** → Cleaned, validated, DQ-flagged, enriched
# MAGIC **Gold** → Aggregated, analytical, business-ready
# MAGIC
# MAGIC The Medallion Architecture is complete.